package Saklient;
use 5.008005;
use strict;
use warnings;

our $VERSION = "0.01";



1;
__END__

=encoding utf-8

=head1 NAME

Saklient - An easy interface to control your resources on SAKURA Cloud.

=head1 SYNOPSIS

    use Saklient::Cloud::API;
    my $api = Saklient::Cloud::API->authorize($YOUR_API_TOKEN, $YOUR_API_SECRET);

    # To access resources in the specified zone
    my $api_is1b = $api->in_zone("is1b");

    # ...

=head1 DESCRIPTION

=head2 INSTALLATION

    # Install dependent packages
    yum install make git openssl-devel
    # or
    apt-get install make git libssl-dev
    
    # Install cpanminus (if not yet)
    curl -L http://cpanmin.us | perl - App::cpanminus
    
    # Install Saklient module by cpanminus
    cpanm git@github.com:sakura-internet/saklient.perl.git

=head2 HOW TO RUN THE SAMPLE CODE

    git clone git@github.com:sakura-internet/saklient.perl.git
    cd saklient.perl
    cp config.sample.sh config.sh
    vi config.sh
    ./test.sh

First, copy B<"config.sample.sh"> file to B<"config.sh"> and edit it.
You have to replace values defined in this script with your API token and secret.
These can be generated by B<"(Account Name) > Settings > API key"> page in the control panel.

After that, just run B<"test.sh">.

=head1 LICENSE

MIT License

=head1 AUTHOR

SAKURA Internet, Inc. E<lt>dev-support-ml@sakura.ad.jpE<gt>

=head1 COPYRIGHT

Copyright (C) 2014 SAKURA Internet, Inc.

=cut

